In [13]:
import numpy as np
import pandas as pd

x = np.matrix(np.random.randint(20, size=12).reshape((3,4)))
print(x)
x.max(0)


[[18 19  3 18]
 [10  0 19  6]
 [ 3  5  9 15]]


matrix([[18, 19, 19, 18]])

In [22]:
def highlight_max(data, color='yellow'):
    '''
    highlight the maximum in a Series or DataFrame
    '''
    attr = 'background-color: {}'.format(color)
    #remove % and cast to float
    data = data.replace('%','', regex=True).astype(float)
    if data.ndim == 1:  # Series from .apply(axis=0) or axis=1
        is_max = data == data.max()
        return [attr if v else '' for v in is_max]
    else:  # from .apply(axis=None)
        is_max = data == data.max().max()
        return pd.DataFrame(np.where(is_max, attr, ''),
                            index=data.index, columns=data.columns)

In [23]:
dfPercent = pd.DataFrame({'2014/2015':['10.3%','9.7%','9.2%'],
                   '2015/2016':['4.8%','100.8%','9.7%']})
dfPercent.style.apply(highlight_max)